import { Subscription, FamilyMember } from '@types/subscription';

export const mockFamilyMembers: FamilyMember[] = [
  { id: '1', name: 'John Doe', avatar: 'https://example.com/john.jpg' },
  { id: '2', name: 'Jane Doe', avatar: 'https://example.com/jane.jpg' },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: '1',
    serviceName: 'Netflix',
    amount: 15.99,
    billingFrequency: 'monthly',
    nextBillingDate: new Date('2024-12-01'),
    category: 'entertainment',
    familyMember: mockFamilyMembers[0],
    status: 'active',
    paymentMethod: 'Visa ****1234',
    autoRenew: true,
    reimbursable: false,
    notes: 'Family plan',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    icon: 'https://example.com/netflix.png',
    syncEnabled: false,
  },
  {
    id: '2',
    serviceName: 'Spotify',
    amount: 9.99,
    billingFrequency: 'monthly',
    nextBillingDate: new Date('2024-12-05'),
    category: 'entertainment',
    status: 'active',
    paymentMethod: 'Mastercard ****5678',
    autoRenew: true,
    reimbursable: false,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    syncEnabled: false,
  },
  {
    id: '3',
    serviceName: 'Adobe Creative Cloud',
    amount: 599.88,
    billingFrequency: 'annual',
    nextBillingDate: new Date('2025-03-01'),
    category: 'productivity',
    familyMember: mockFamilyMembers[1],
    status: 'active',
    paymentMethod: 'Visa ****1234',
    autoRenew: true,
    reimbursable: true,
    notes: 'Work expense',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
    syncEnabled: false,
  },
  {
    id: '4',
    serviceName: 'ChatGPT Plus',
    amount: 20.0,
    billingFrequency: 'monthly',
    nextBillingDate: new Date('2024-11-28'),
    category: 'productivity',
    status: 'active',
    paymentMethod: 'Visa ****1234',
    autoRenew: true,
    reimbursable: true,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
    syncEnabled: false,
  },
  {
    id: '5',
    serviceName: 'Gym Membership',
    amount: 50.0,
    billingFrequency: 'monthly',
    nextBillingDate: new Date('2024-12-15'),
    category: 'health-fitness',
    status: 'paused',
    paymentMethod: 'Debit ****9012',
    autoRenew: false,
    reimbursable: false,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-05-01'),
    syncEnabled: false,
  },
  {
    id: '6',
    serviceName: 'Coursera',
    amount: 399.0,
    billingFrequency: 'annual',
    nextBillingDate: new Date('2025-06-01'),
    category: 'education',
    status: 'active',
    paymentMethod: 'Visa ****1234',
    autoRenew: true,
    reimbursable: true,
    notes: 'Professional development',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-01'),
    syncEnabled: false,
  },
  {
    id: '7',
    serviceName: 'Figma Pro',
    amount: 12.0,
    billingFrequency: 'monthly',
    nextBillingDate: new Date('2024-11-26'),
    category: 'productivity',
    status: 'trial',
    paymentMethod: 'Visa ****1234',
    autoRenew: true,
    reimbursable: false,
    notes: 'Trial ends soon',
    createdAt: new Date('2024-10-26'),
    updatedAt: new Date('2024-10-26'),
    syncEnabled: false,
  },
  {
    id: '8',
    serviceName: 'Lifetime Software License',
    amount: 299.0,
    billingFrequency: 'one-time',
    nextBillingDate: new Date('2024-07-01'),
    category: 'productivity',
    status: 'active',
    paymentMethod: 'Visa ****1234',
    autoRenew: false,
    reimbursable: false,
    notes: 'One-time purchase',
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-07-01'),
    syncEnabled: false,
  },
  {
    id: '9',
    serviceName: 'Dropbox',
    amount: 119.88,
    billingFrequency: 'annual',
    nextBillingDate: new Date('2024-11-25'),
    category: 'utilities',
    status: 'active',
    paymentMethod: 'Visa ****1234',
    autoRenew: true,
    reimbursable: false,
    createdAt: new Date('2023-11-25'),
    updatedAt: new Date('2023-11-25'),
    syncEnabled: false,
  },
  {
    id: '10',
    serviceName: 'Amazon Prime',
    amount: 139.0,
    billingFrequency: 'annual',
    nextBillingDate: new Date('2025-02-15'),
    category: 'shopping',
    status: 'cancelled',
    paymentMethod: 'Visa ****1234',
    autoRenew: false,
    reimbursable: false,
    notes: 'Cancelled, expires next year',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-10-15'),
    syncEnabled: false,
  },
];

export const createMockSubscription = (
  overrides: Partial<Subscription> = {}
): Subscription => ({
  id: 'mock-id',
  serviceName: 'Mock Service',
  amount: 10.0,
  billingFrequency: 'monthly',
  nextBillingDate: new Date('2024-12-01'),
  category: 'other',
  status: 'active',
  paymentMethod: 'Visa ****0000',
  autoRenew: true,
  reimbursable: false,
  createdAt: new Date(),
  updatedAt: new Date(),
  syncEnabled: false,
  ...overrides,
});
